name: bunq
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Jogboms <jeremiahogbomo@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  pointycastle: ^1.0.0
  asn1lib: ^0.5.3
  uuid: ^2.0.1
  http: ^0.12.0
  built_value: ^6.4.0
  built_collection: ^4.2.0
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  test_coverage: ^0.2.0
  build_runner: ^1.3.1
  built_value_generator: ^6.4.0
